### ISSUE TITLE
what is the negative prompt in the paper

### ISSUE THREAD

**Issue by xmu-xiaoma666** [alvinliu0/HumanGaussian#1]
![image](https://github.com/alvinliu0/HumanGaussian/assets/33897496/e4d1ce00-d9df-474a-8c7a-375cada274e7)

Thanks for your great job! 
I wonder what is the negative prompt used in your implementation!

**Comment by alvinliu0** [comment]
Hi, many thanks for your interest in our work:)

The negative prompt used is 

"shadow, dark face, colorful hands, eyeglass, glasses, (deformed iris, deformed pupils, semi-realistic, cgi, 3d, render, sketch, cartoon, drawing, anime:1.4), text, close up, cropped, out of frame, worst quality, low quality, jpeg artifacts, ugly, duplicate, morbid, mutilated, extra fingers, mutated hands, poorly drawn hands, poorly drawn face, mutation, deformed, blurry, dehydrated, bad anatomy, bad proportions, extra limbs, cloned face, disfigured, gross proportions, malformed limbs, missing arms, missing legs, extra arms, extra legs, fused fingers, too many fingers, long neck"

As indicated in [L59](https://github.com/alvinliu0/HumanGaussian/blob/main/configs/test.yaml#L59) of the config file.

Best
