### ISSUE TITLE
render animation w/o gui

### ISSUE THREAD

**Issue by ggxxii** [alvinliu0/HumanGaussian#10]
Hi, 

It seems my linux cannot install dearpygui, I'm wondering is it possible to render the animation without the GUI?

**Comment by alvinliu0** [comment]
Hi,

could you please try turn off the gui to see whether it can animate? It should be able to save a video file even if no GUI is used.

Best

**Comment by ggxxii** [comment]
yes!! I figure out output the animation video by annotating the import line, thank you~
