### ISSUE TITLE
Why the size of avatars are the almost same??

### ISSUE THREAD

**Issue by sunwonlikeyou** [alvinliu0/HumanGaussian#16]
I made the Lionel Messi, Lebron James,,,
But ply files are almost same size. And I also changed betas( Big Height for Lebron James) but Size was same. Are there module to optimize shape for specific characters?

**Comment by alvinliu0** [comment]
Hi, you can change the body shape by specifying different body shape parameters [here](https://github.com/alvinliu0/HumanGaussian/blob/main/threestudio/utils/poser.py#L319), we have tested several samples and it can indeed change body shape.
![image](https://github.com/alvinliu0/HumanGaussian/assets/45938041/852ed18b-87c0-4ea5-88be-8b2664c28a0a)

**Comment by sunwonlikeyou** [comment]
Oh, I checked it. Thanks!!
