### ISSUE TITLE
Clarification on Size-Conditioned Gaussian Pruning

### ISSUE THREAD

**Issue by sangminkim-99** [alvinliu0/HumanGaussian#19]
Hi @alvinliu0,

Firstly, I want to express my appreciation for sharing your exceptional work.

I have a question regarding the Size-Conditioned Gaussian Pruning technique outlined in your paper. 
Specifically, I noted a statement mentioning that "such floating artifacts emerge as tiny size Gaussians during the 3DGS densification process of cloning and splitting." 
However, upon reviewing the results of the ablation study, it appears that the pruning is primarily affecting large Gaussians rather than the smaller ones.

Moreover, upon examining the code [here](https://github.com/alvinliu0/HumanGaussian/blob/84ef6918c04cea4374cb75d394e9bf58f2f5ca4e/gaussiansplatting/scene/gaussian_model.py#L426), it seems that the intention is to remove the larger Gaussians.

Could you please clarify this discrepancy? 
I want to ensure I'm interpreting the methodology correctly.

Thank you.

**Comment by alvinliu0** [comment]
Hi,

Many thanks for your interest in our work! Yes, you are right, this is a typo in the original version, where the artifacts are large-size, tiny-opacity floating Gaussians to be pruned. We have already corrected it in the camera-ready version and the [latest arxiv version](https://arxiv.org/abs/2311.17061v2). Please kindly refer to it.

Best
