### ISSUE TITLE
SyntaxError: invalid syntax，but there seems to be no problem with the code

### ISSUE THREAD

**Issue by Piggy-ch** [alvinliu0/HumanGaussian#2]
When I run the command 
`python launch.py --config configs/test.yaml --train --gpu 0 system.prompt_processor.prompt="A boy with a beanie wearing a hoodie and joggers"`
The following error is reported：
File "launch.py", line 38
    record.levelname = f"{color_start}[{record.levelname}]"
                                                                                        ^
SyntaxError: invalid syntax

I don't think there's anything wrong with that.I don't know where the problem lies.
Among them, I installed xformers through github wheel.

My environment is as follows：
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main
_openmp_mutex             5.1                       1_gnu
absl-py                   2.0.0                    pypi_0    pypi
accelerate                0.25.0                   pypi_0    pypi
aiofiles                  23.2.1                   pypi_0    pypi
aiohttp                   3.9.1                    pypi_0    pypi
aiosignal                 1.3.1                    pypi_0    pypi
altair                    5.2.0                    pypi_0    pypi
annotated-types           0.6.0                    pypi_0    pypi
antlr4-python3-runtime    4.9.3                    pypi_0    pypi
anyio                     3.7.1                    pypi_0    pypi
appdirs                   1.4.4                    pypi_0    pypi
async-timeout             4.0.3                    pypi_0    pypi
attrs                     23.1.0                   pypi_0    pypi
bitsandbytes              0.38.1                   pypi_0    pypi
bzip2                     1.0.8                h7b6447c_0
ca-certificates           2023.08.22           h06a4308_0
cachetools                5.3.2                    pypi_0    pypi
certifi                   2022.12.7                pypi_0    pypi
chardet                   5.2.0                    pypi_0    pypi
charset-normalizer        2.1.1                    pypi_0    pypi
click                     8.1.7                    pypi_0    pypi
clip                      1.0                      pypi_0    pypi
cmake                     3.25.0                   pypi_0    pypi
colorama                  0.4.6                    pypi_0    pypi
colorlog                  6.8.0                    pypi_0    pypi
contourpy                 1.2.0                    pypi_0    pypi
controlnet-aux            0.0.7                    pypi_0    pypi
cycler                    0.12.1                   pypi_0    pypi
diff-gaussian-rasterization 0.0.0                    pypi_0    pypi
diffusers                 0.24.0                   pypi_0    pypi
docker-pycreds            0.4.0                    pypi_0    pypi
einops                    0.7.0                    pypi_0    pypi
envlight                  0.1.0                    pypi_0    pypi
exceptiongroup            1.2.0                    pypi_0    pypi
fastapi                   0.104.1                  pypi_0    pypi
ffmpy                     0.3.1                    pypi_0    pypi
filelock                  3.9.0                    pypi_0    pypi
fonttools                 4.46.0                   pypi_0    pypi
frozenlist                1.4.0                    pypi_0    pypi
fsspec                    2023.12.0                pypi_0    pypi
ftfy                      6.1.3                    pypi_0    pypi
gitdb                     4.0.11                   pypi_0    pypi
gitpython                 3.1.40                   pypi_0    pypi
google-auth               2.24.0                   pypi_0    pypi
google-auth-oauthlib      1.1.0                    pypi_0    pypi
gradio                    4.7.1                    pypi_0    pypi
gradio-client             0.7.0                    pypi_0    pypi
grpcio                    1.59.3                   pypi_0    pypi
h11                       0.14.0                   pypi_0    pypi
httpcore                  1.0.2                    pypi_0    pypi
httpx                     0.25.2                   pypi_0    pypi
huggingface-hub           0.19.4                   pypi_0    pypi
idna                      3.4                      pypi_0    pypi
imageio                   2.33.0                   pypi_0    pypi
imageio-ffmpeg            0.4.9                    pypi_0    pypi
importlib-metadata        7.0.0                    pypi_0    pypi
importlib-resources       6.1.1                    pypi_0    pypi
jaxtyping                 0.2.24                   pypi_0    pypi
jinja2                    3.1.2                    pypi_0    pypi
jsonschema                4.20.0                   pypi_0    pypi
jsonschema-specifications 2023.11.2                pypi_0    pypi
kiwisolver                1.4.5                    pypi_0    pypi
kornia                    0.7.0                    pypi_0    pypi
lazy-loader               0.3                      pypi_0    pypi
ld_impl_linux-64          2.38                 h1181459_1
libffi                    3.4.4                h6a678d5_0
libgcc-ng                 11.2.0               h1234567_1
libgomp                   11.2.0               h1234567_1
libigl                    2.5.0                    pypi_0    pypi
libstdcxx-ng              11.2.0               h1234567_1
libuuid                   1.41.5               h5eee18b_0
lightning                 2.1.2                    pypi_0    pypi
lightning-utilities       0.10.0                   pypi_0    pypi
lit                       15.0.7                   pypi_0    pypi
lxml                      4.9.3                    pypi_0    pypi
mapbox-earcut             1.0.1                    pypi_0    pypi
markdown                  3.5.1                    pypi_0    pypi
markdown-it-py            3.0.0                    pypi_0    pypi
markupsafe                2.1.3                    pypi_0    pypi
matplotlib                3.8.2                    pypi_0    pypi
mdurl                     0.1.2                    pypi_0    pypi
mpmath                    1.3.0                    pypi_0    pypi
multidict                 6.0.4                    pypi_0    pypi
ncurses                   6.4                  h6a678d5_0
nerfacc                   0.5.2                    pypi_0    pypi
networkx                  3.0                      pypi_0    pypi
ninja                     1.11.1.1                 pypi_0    pypi
numpy                     1.24.1                   pypi_0    pypi
nvdiffrast                0.3.1                    pypi_0    pypi
oauthlib                  3.2.2                    pypi_0    pypi
omegaconf                 2.3.0                    pypi_0    pypi
opencv-python             4.8.1.78                 pypi_0    pypi
openssl                   3.0.12               h7f8727e_0
orjson                    3.9.10                   pypi_0    pypi
packaging                 23.2                     pypi_0    pypi
pandas                    2.1.3                    pypi_0    pypi
pillow                    9.3.0                    pypi_0    pypi
pip                       23.3.1          py310h06a4308_0
plyfile                   1.0.2                    pypi_0    pypi
protobuf                  4.23.4                   pypi_0    pypi
psutil                    5.9.6                    pypi_0    pypi
pyasn1                    0.5.1                    pypi_0    pypi
pyasn1-modules            0.3.0                    pypi_0    pypi
pycollada                 0.7.2                    pypi_0    pypi
pydantic                  2.5.2                    pypi_0    pypi
pydantic-core             2.14.5                   pypi_0    pypi
pydub                     0.25.1                   pypi_0    pypi
pygments                  2.17.2                   pypi_0    pypi
pymcubes                  0.1.4                    pypi_0    pypi
pyparsing                 3.1.1                    pypi_0    pypi
python                    3.10.13              h955ad1f_0
python-dateutil           2.8.2                    pypi_0    pypi
python-multipart          0.0.6                    pypi_0    pypi
pytorch-lightning         2.1.2                    pypi_0    pypi
pytz                      2023.3.post1             pypi_0    pypi
pyyaml                    6.0.1                    pypi_0    pypi
readline                  8.2                  h5eee18b_0
referencing               0.31.1                   pypi_0    pypi
regex                     2023.10.3                pypi_0    pypi
requests                  2.28.1                   pypi_0    pypi
requests-oauthlib         1.3.1                    pypi_0    pypi
rich                      13.7.0                   pypi_0    pypi
rpds-py                   0.13.2                   pypi_0    pypi
rsa                       4.9                      pypi_0    pypi
rtree                     1.1.0                    pypi_0    pypi
safetensors               0.4.1                    pypi_0    pypi
scikit-image              0.22.0                   pypi_0    pypi
scipy                     1.11.4                   pypi_0    pypi
seaborn                   0.13.0                   pypi_0    pypi
semantic-version          2.10.0                   pypi_0    pypi
sentencepiece             0.1.99                   pypi_0    pypi
sentry-sdk                1.38.0                   pypi_0    pypi
setproctitle              1.3.3                    pypi_0    pypi
setuptools                68.0.0          py310h06a4308_0
shapely                   2.0.2                    pypi_0    pypi
shellingham               1.5.4                    pypi_0    pypi
simple-knn                0.0.0                    pypi_0    pypi
six                       1.16.0                   pypi_0    pypi
smmap                     5.0.1                    pypi_0    pypi
smplx                     0.1.28                   pypi_0    pypi
sniffio                   1.3.0                    pypi_0    pypi
sqlite                    3.41.2               h5eee18b_0
starlette                 0.27.0                   pypi_0    pypi
svg-path                  6.3                      pypi_0    pypi
sympy                     1.12                     pypi_0    pypi
taming-transformers-rom1504 0.0.6                    pypi_0    pypi
tensorboard               2.15.1                   pypi_0    pypi
tensorboard-data-server   0.7.2                    pypi_0    pypi
tifffile                  2023.9.26                pypi_0    pypi
timm                      0.9.12                   pypi_0    pypi
tinycudann                1.7                      pypi_0    pypi
tk                        8.6.12               h1ccaba5_0
tokenizers                0.15.0                   pypi_0    pypi
tomlkit                   0.12.0                   pypi_0    pypi
toolz                     0.12.0                   pypi_0    pypi
torch                     2.0.1+cu117              pypi_0    pypi
torchaudio                2.0.2+cu117              pypi_0    pypi
torchmetrics              1.2.1                    pypi_0    pypi
torchvision               0.15.2+cu117             pypi_0    pypi
tqdm                      4.66.1                   pypi_0    pypi
transformers              4.35.2                   pypi_0    pypi
trimesh                   3.21.7                   pypi_0    pypi
triton                    2.0.0                    pypi_0    pypi
typeguard                 2.13.3                   pypi_0    pypi
typer                     0.9.0                    pypi_0    pypi
typing-extensions         4.8.0                    pypi_0    pypi
tzdata                    2023.3                   pypi_0    pypi
urllib3                   1.26.13                  pypi_0    pypi
uvicorn                   0.24.0.post1             pypi_0    pypi
wandb                     0.16.0                   pypi_0    pypi
wcwidth                   0.2.12                   pypi_0    pypi
websockets                11.0.3                   pypi_0    pypi
werkzeug                  3.0.1                    pypi_0    pypi
wheel                     0.41.2          py310h06a4308_0
xatlas                    0.0.8                    pypi_0    pypi
xformers                  0.0.23+246b45c.d20231204          pypi_0    pypi
xxhash                    3.4.1                    pypi_0    pypi
xz                        5.4.2                h5eee18b_0
yarl                      1.9.3                    pypi_0    pypi
zipp                      3.17.0                   pypi_0    pypi
zlib                      1.2.13               h5eee18b_0

**Comment by alvinliu0** [comment]
Hi, many thanks for your interest in our work:)

I guess this is a dependency-related issue. I have just updated the installation dependency, could you please kindly check if this can resolve your problem? Btw, since our codebase is developed based on ThreeStudio and GaussianDreamer. Maybe you could kindly refer to them for installation:)

Best

**Comment by Piggy-ch** [comment]
> Hi, many thanks for your interest in our work:)
> 
> I guess this is a dependency-related issue. I have just updated the installation dependency, could you please kindly check if this can resolve your problem? Btw, since our codebase is developed based on ThreeStudio and GaussianDreamer. Maybe you could kindly refer to them for installation:)
> 
> Best

Thank you for your reply. I tried to update the installation dependency, but still couldn't solve my problem. Additionally, I would like to clarify that the pip installation of xform only supports pytorch=2.1.0. I solved the problem by installing pytorch and xform through Conda, but still couldn't report the same error

**Comment by Piggy-ch** [comment]
> Hi, many thanks for your interest in our work:)
> 
> I guess this is a dependency-related issue. I have just updated the installation dependency, could you please kindly check if this can resolve your problem? Btw, since our codebase is developed based on ThreeStudio and GaussianDreamer. Maybe you could kindly refer to them for installation:)
> 
> Best
 Sorry, it’s my problem. Your code doesn’t have any issues. Thank you for your reply and attention.

**Comment by Piggy-ch** [comment]
> Hi, many thanks for your interest in our work:)
> 
> I guess this is a dependency-related issue. I have just updated the installation dependency, could you please kindly check if this can resolve your problem? Btw, since our codebase is developed based on ThreeStudio and GaussianDreamer. Maybe you could kindly refer to them for installation:)
> 
> Best

 Sorry, it’s my problem. Your code doesn’t have any issues. Thank you for your reply and attention.
