### ISSUE TITLE
cuda issues

### ISSUE THREAD

**Issue by zhou431496** [alvinliu0/HumanGaussian#22]
When running the script, the input is on cuda, but the parameter is on cpu. How to solve this problem

**Comment by alvinliu0** [comment]
Hi,

Could you provide more details on such a bug? We have not encountered such an issues before.

Best

**Comment by zhou431496** [comment]
> Hi,
> 
> Could you provide more details on such a bug? We have not encountered such an issues before.
> 
> Best
解决啦，请问你微调时，用了多大的数据，我发现你的结果在一些提示上比其他方法更好，是模型更好还是说采用更多的数据训练

**Comment by alvinliu0** [comment]
Hi,

We do not do the fine-tuning. We follow the common 2D-lifting pipeline (i.e., DreamFusion SDS) to train in a per-prompt optimization setting. Each model is just trained from scratch based on that certain prompt, so no fine-tuning is needed. The performance gain is from the model and design itself, since all the compared baselines all follow such a per-prompt optimization paradigm. The comparison is conducted in a fully fair setting.

Best

**Comment by zhou431496** [comment]
> 你好
> 
> 我们不进行微调。我们遵循常见的 2D 提升管道（即 DreamFusion SDS）在每个提示的优化设置中进行训练。每个模型都是根据特定的提示从头开始训练的，因此不需要微调。性能提升来自模型和设计本身，因为所有比较的基线都遵循这种按提示优化范式。比较是在完全公平的环境中进行的。
> 
> 最好

感谢你的回复, 正如你所说的,在优化中设置训练,但是在优化之前,往往会微调SD模型,因为RGB,normal和depth的分布往往并不相同, 在微调SD过程中是不是用了更大的数据集, 而不是Humannorm 只使用2950个人体模型做微调.

**Comment by alvinliu0** [comment]
Yes, we use a subset from LAION. The model itself is more reasonable, as the fine-tuned depth and rgb are spatially aligned, in contrast to the baselines that are independently trained and render misaligned depth and rgb.

**Comment by zhou431496** [comment]
> Yes, we use a subset from LAION. The model itself is more reasonable, as the fine-tuned depth and rgb are spatially aligned, in contrast to the baselines that are independently trained and render misaligned depth and rgb.
感谢你的解答,LAION子集是LAION-Human嘛

**Comment by gushengbo** [comment]
> When running the script, the input is on cuda, but the parameter is on cpu. How to solve this problem

请问能够告诉我怎么解决这个问题吗？

**Comment by alvinliu0** [comment]
> > Yes, we use a subset from LAION. The model itself is more reasonable, as the fine-tuned depth and rgb are spatially aligned, in contrast to the baselines that are independently trained and render misaligned depth and rgb.
> > 感谢你的解答,LAION子集是LAION-Human嘛

Yeah, you can use LAION-Human. But in our practice, we use detection tools to filter our human images from LAION fullset

**Comment by zhou431496** [comment]
> > When running the script, the input is on cuda, but the parameter is on cpu. How to solve this problem
> 
> 请问能够告诉我怎么解决这个问题吗？

具体我也不清楚,我就是换了一台设备装的就可以了,没有帮到你十分抱歉

**Comment by zhou431496** [comment]
> > > Yes, we use a subset from LAION. The model itself is more reasonable, as the fine-tuned depth and rgb are spatially aligned, in contrast to the baselines that are independently trained and render misaligned depth and rgb.
> > > 感谢你的解答,LAION子集是LAION-Human嘛
> 
> Yeah, you can use LAION-Human. But in our practice, we use detection tools to filter our human images from LAION fullset
请问你会开源这个数据集嘛

**Comment by alvinliu0** [comment]
Hi, due to the copyright issues we can not release the images. You can apply to download the dataset and filter out human subset either by off-the-shelf detectors, or simply those contain words like "human", "people", "man", "woman" in prompts.

**Comment by zhou431496** [comment]
> Hi, due to the copyright issues we can not release the images. You can apply to download the dataset and filter out human subset either by off-the-shelf detectors, or simply those contain words like "human", "people", "man", "woman" in prompts.

十分感谢你的回复

**Comment by gushengbo** [comment]
> > > When running the script, the input is on cuda, but the parameter is on cpu. How to solve this problem
> > 
> > 
> > 请问能够告诉我怎么解决这个问题吗？
> 
> 具体我也不清楚,我就是换了一台设备装的就可以了,没有帮到你十分抱歉

好，感谢！！

**Comment by HelloRicky123** [comment]
> > > > When running the script, the input is on cuda, but the parameter is on cpu. How to solve this problem
> > > 
> > > 
> > > 请问能够告诉我怎么解决这个问题吗？
> > 
> > 
> > 具体我也不清楚,我就是换了一台设备装的就可以了,没有帮到你十分抱歉
> 
> 好，感谢！！

Hi,

It looks like caused by different versions of diffuser. In my diffuser of latest version, the 'to' function takes in 'dtype' and 'device'  parameters. But humangaussian inputs with 'torch' as prefix. The following line may solve the problem.

![image](https://github.com/user-attachments/assets/78367c54-6187-408d-8f4a-795041794382)
