### ISSUE TITLE
Error in running the launch.py

### ISSUE THREAD

**Issue by vrk7** [alvinliu0/HumanGaussian#7]
I get the below error when I am launching the launch.py.

python launch.py --config configs/test.yaml --train --gpu 0 system.prompt_processor.prompt="A boy with a beanie wearing a hoodie and joggers"

WARNING[XFORMERS]: xFormers can't load C++/CUDA extensions. xFormers was built for:
    PyTorch 2.1.0+cu121 with CUDA 1201 (you have 2.1.0)
    Python  3.10.13 (you have 3.10.13)
  Please reinstall xformers (see https://github.com/facebookresearch/xformers#installing-xformers)
  Memory-efficient attention, SwiGLU, sparse and more won't be available.
  Set XFORMERS_MORE_DETAILS=1 for more details
Seed set to 0
[INFO] Using 16bit Automatic Mixed Precision (AMP)
[INFO] GPU available: True (cuda), used: True
[INFO] TPU available: False, using: 0 TPU cores
[INFO] IPU available: False, using: 0 IPUs
[INFO] HPU available: False, using: 0 HPUs
[INFO] You are using a CUDA device ('NVIDIA RTX A6000') that has Tensor Cores. To properly utilize them, you should set `torch.set_float32_matmul_precision('medium' | 'high')` which will trade-off precision for performance. For more details, read https://pytorch.org/docs/stable/generated/torch.set_float32_matmul_precision.html#torch.set_float32_matmul_precision
[INFO] LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
Number of points at initialisation :  100000
[INFO] 
  | Name | Type | Params
------------------------------
------------------------------
0         Trainable params
0         Non-trainable params
0         Total params
0.000     Total estimated model params size (MB)
[INFO] Validation results will be saved to /save/name-of-this-experiment-run/A_boy_with_a_beanie_wearing_a_hoodie_and_joggers@20231224-034127/save
[INFO] Using prompt [A boy with a beanie wearing a hoodie and joggers] and negative prompt [shadow, dark face, colorful hands, eyeglass, glasses, (deformed iris, deformed pupils, semi-realistic, cgi, 3d, render, sketch, cartoon, drawing, anime:1.4), text, close up, cropped, out of frame, worst quality, low quality, jpeg artifacts, ugly, duplicate, morbid, mutilated, extra fingers, mutated hands, poorly drawn hands, poorly drawn face, mutation, deformed, blurry, dehydrated, bad anatomy, bad proportions, extra limbs, cloned face, disfigured, gross proportions, malformed limbs, missing arms, missing legs, extra arms, extra legs, fused fingers, too many fingers, long neck]
[INFO] Using view-dependent prompts [side]:[A boy with a beanie wearing a hoodie and joggers, side view] [front]:[A boy with a beanie wearing a hoodie and joggers, front view] [back]:[A boy with a beanie wearing a hoodie and joggers, back view] [overhead]:[A boy with a beanie wearing a hoodie and joggers, overhead view]
[INFO] Loading Texture-Structure Joint Model ...
The config attributes {'decay': 0.9999, 'inv_gamma': 1.0, 'min_decay': 0.0, 'optimization_step': 152000, 'power': 0.6666666666666666, 'update_after_step': 0, 'use_ema_warmup': False} were passed to UNet2DConditionModel, but are not expected and will be ignored. Please verify your config.json configuration file.
Traceback (most recent call last):
  File "/opt/conda/lib/python3.10/site-packages/diffusers/models/modeling_utils.py", line 111, in load_state_dict
    return safetensors.torch.load_file(checkpoint_file, device="cpu")
  File "/opt/conda/lib/python3.10/site-packages/safetensors/torch.py", line 308, in load_file
    with safe_open(filename, framework="pt", device=device) as f:
safetensors_rust.SafetensorError: Error while deserializing header: HeaderTooLarge

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/conda/lib/python3.10/site-packages/diffusers/models/modeling_utils.py", line 122, in load_state_dict
    raise ValueError(
ValueError: Unable to locate the file ./texture_structure_joint/unet_ema/config.json which is necessary to load this pretrained model. Make sure you have saved the model properly.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/HumanGaussian/launch.py", line 239, in <module>
    main(args, extras)
  File "/HumanGaussian/launch.py", line 182, in main
    trainer.fit(system, datamodule=dm, ckpt_path=cfg.resume)
  File "/opt/conda/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 544, in fit
    call._call_and_handle_interrupt(
  File "/opt/conda/lib/python3.10/site-packages/pytorch_lightning/trainer/call.py", line 44, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 580, in _fit_impl
    self._run(model, ckpt_path=ckpt_path)
  File "/opt/conda/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 970, in _run
    call._call_lightning_module_hook(self, "on_fit_start")
  File "/opt/conda/lib/python3.10/site-packages/pytorch_lightning/trainer/call.py", line 157, in _call_lightning_module_hook
    output = fn(*args, **kwargs)
  File "/HumanGaussian/threestudio/systems/GaussianDreamer.py", line 314, in on_fit_start
    self.guidance = threestudio.find(self.cfg.guidance_type)(self.cfg.guidance)
  File "/HumanGaussian/threestudio/utils/base.py", line 63, in __init__
    self.configure(*args, **kwargs)
  File "/HumanGaussian/threestudio/models/guidance/dual_branch_guidance.py", line 97, in configure
    unet = UNet2DConditionModel.from_pretrained(self.cfg.model_key, subfolder="unet_ema").to(self.weights_dtype)
  File "/opt/conda/lib/python3.10/site-packages/diffusers/models/modeling_utils.py", line 800, in from_pretrained
    state_dict = load_state_dict(model_file, variant=variant)
  File "/opt/conda/lib/python3.10/site-packages/diffusers/models/modeling_utils.py", line 127, in load_state_dict
    raise OSError(
OSError: Unable to load weights from checkpoint file for './texture_structure_joint/unet_ema/config.json' at './texture_structure_joint/unet_ema/config.json'. If you tried to load a PyTorch model from a TF 2.0 checkpoint, please set from_tf=True.

Kindly help me with this.

**Comment by DrawingProcess** [comment]
How to solved it? I have a same problem.

```
OSError: Unable to load weights from checkpoint file for './texture_structure_joint/unet_ema/config.json' at './texture_structure_joint/unet_ema/config.json'. If you tried to load a PyTorch model from a TF 2.0 checkpoint, please set from_tf=True.
```
